"""Prompt and response phrasing helpers for natural support voice tone."""

from __future__ import annotations

import random


OPENING_DISCLOSURE = (
    "Hi, I am Mia, a virtual support assistant for Simple Loans."
)

UNANSWERABLE_FALLBACK = (
    "I am unable to provide the answer for that, if you'd like I can note it down "
    "and make sure one of our representatives gets back to you."
)

ESCALATION_MESSAGE = (
    "Thank you for flagging this. I am escalating your case now to a human "
    "specialist for priority handling."
)

FOLLOWUP_CHANNEL_QUESTION = (
    "Understood. I can arrange a follow-up with a specialist. "
    "Which contact channel do you prefer?"
)

FOLLOWUP_TIME_QUESTION = "Thanks, I noted that. What time works best for a follow-up?"

FOLLOWUP_CONFIRM_TEMPLATE = (
    "Perfect, I have noted a follow-up via {channel} around {when}. "
    "A human specialist will continue from here."
)

NO_FOLLOWUP_CLOSE = "No problem. If anything changes, we are here to help."

VOICE_SYSTEM_INSTRUCTIONS = """
You are a natural, concise, empathetic Simple Loans voice support assistant.

Rules you must always follow:
1) Only answer from the internal policy response generated by the local support engine.
2) Do not invent policy, pricing, legal details, or timelines.
3) Keep responses short and clear for voice calls.
4) Ask one question at a time.
5) Confirm resolution before ending when relevant.
6) If policy is not found, use the provided fallback sentence.
""".strip()

def resolution_question(rng: random.Random) -> str:
    options = [
        "Did this answer your question?",
        "Did that clear things up for you?",
        "Does this resolve what you needed?",
    ]
    return rng.choice(options)


def closing_message(rng: random.Random) -> str:
    options = [
        "Great, happy to help. If anything else comes up, I am here.",
        "Glad that helped. Reach out anytime if you need more support.",
        "Perfect. If you need anything else, I can help.",
    ]
    return rng.choice(options)
